package part_03._02_Exceptions._8_The_try_with_resources_Statement;

public class _8_The_try_with_resources_Statement {
 
	public static void main(String[] args) {
 
	}

}
